scan_filter_chain:
# - name: shadows
#   type: laser_filters/ScanShadowsFilter
#   params:
#     min_angle: 0
#     max_angle: 360
#     neighbors: 20
#     window: 1
# - name: dark_shadows
#   type: laser_filters/LaserScanIntensityFilter
#   params:
#     lower_threshold: 100
#     upper_threshold: 10000
#     disp_histogram: 0
- name: range
  type: laser_filters/LaserScanRangeFilter
  params:
    use_message_range_limits: false
    lower_threshold: 0.25
    upper_threshold: .inf
    lower_replacement_value: -.inf
    upper_replacement_value: .inf
- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: lidar_link
    min_x: -0.25
    max_x: 0.25
    min_y: -0.25
    max_y: 0.25
    min_z: -1.0
    max_z: 1.0
# - name: box2
#   type: laser_filters/LaserScanBoxFilter
#   params:
#     box_frame: lidar_link
#     min_x: 0.0
#     max_x: 0.42
#     min_y: 0.0
#     max_y: 0.42
#     min_z: 0.0
#     max_z: 1.0